# Generated by Django 3.2.3 on 2021-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
