# Generated by Django 3.2.4 on 2021-06-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_usersprofile_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='otp',
            field=models.IntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
