# Generated by Django 3.2.4 on 2021-06-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_usersprofile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='otp',
            field=models.IntegerField(default=None, max_length=6),
        ),
    ]
