# Generated by Django 3.2.4 on 2021-06-29 18:01

import Patients.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_photo', models.FileField(upload_to='Images/%Y/%m/%d', validators=[Patients.validators.validate_file_extension_of_pic])),
                ('disease', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('documents', models.FileField(upload_to='documents/%Y/%m/%d', validators=[Patients.validators.validate_file_extension])),
                ('doctor_name', models.CharField(max_length=30)),
                ('required_amount', models.IntegerField()),
                ('upi_id', models.CharField(max_length=50)),
                ('collected_amount', models.IntegerField(null=True)),
                ('admin_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('screenshot', models.FileField(upload_to='PaymentProofs/%Y/%m/%d', validators=[Patients.validators.validate_file_extension_of_pic])),
                ('admin_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=30)),
            ],
        ),
    ]
