# Generated by Django 3.2.4 on 2021-07-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='collected_amount',
            field=models.IntegerField(default=0),
        ),
    ]
