# Generated by Django 3.2.4 on 2021-06-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_alter_patients_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='documents',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
