# Generated by Django 3.2.4 on 2021-06-29 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Hospitals',
            new_name='Hospital',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Relationships',
            new_name='Relationship',
        ),
    ]
