# Generated by Django 3.2.4 on 2021-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_auto_20210629_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
