# Generated by Django 3.2.4 on 2021-06-23 17:26

import Patients.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_alter_patients_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_photo',
            field=models.FileField(default=0, upload_to='Images/%Y/%m/%d', validators=[Patients.validators.validate_file_extension_of_pic]),
            preserve_default=False,
        ),
    ]
