# Generated by Django 3.2.5 on 2021-07-19 16:02

import Patients.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patients', '0004_payment_user_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('patient_photo', models.FileField(upload_to='Images/%Y/%m/%d', validators=[Patients.validators.validate_file_extension_of_pic])),
                ('disease', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('documents', models.FileField(upload_to='documents/%Y/%m/%d', validators=[Patients.validators.validate_file_extension])),
                ('doctor_name', models.CharField(max_length=30)),
                ('required_amount', models.IntegerField()),
                ('upi_id', models.CharField(max_length=50)),
                ('collected_amount', models.IntegerField(default=0)),
                ('admin_verified', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.category')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.hospital')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.relationship')),
            ],
        ),
    ]
