# Generated by Django 3.2.4 on 2021-06-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0005_patients_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='upi_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
